# Site settings
title: jvp.io
email: jasonvperrin@gmail.com
description: >
  The personal site for Jason Perrin,
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jvp.io" # the base hostname & protocol for your site
twitter_username: jvperrin
github_username:  jvperrin

# Build settings
markdown: kramdown

sass:
  style: compressed

exclude:
  - Gruntfile.js
  - package.json
  - node_modules
